# Generated by Django 2.2.6 on 2019-11-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_auto_20191107_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='course.Course'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
