# Generated by Django 2.2.6 on 2019-11-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20191103_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correctOption',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
