# Generated by Django 2.2.6 on 2019-11-04 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_auto_20191104_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='user',
            new_name='users',
        ),
        migrations.AddField(
            model_name='quiz',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
