# Generated by Django 2.2.6 on 2019-11-05 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_plantflixuser_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantflixuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='plantflixuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='plantflixuser',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='plantflixuser',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantflixuser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
